### ISSUE TITLE
upload of VODML XML

### ISSUE THREAD

**Issue by loumir** [ivoa-std/PhotDM#102]
this topic came in pR #86 addressed by Markus 
[pointing to VODML xml  ](https://github.com/ivoa-std/PhotDM/pull/86#discussion_r880121918)

we should upload the xml description of the model at http://ivoa.net/xml 
the file should contain the version nb , as PhotDM1.1 is the first version to support a VODML description of the Photometry Data Model. PhotDM1.0 had none. 

I suggest this name : 
Phot-v1_1.vo-dml.xml like for other models given as example here 
https://ivoa.net/xml/VODML/20191125/Provenance-v1.vo-dml.xml
https://ivoa.net/xml/VODML/Coords-v1.vo-dml.xml

I am ready to submit it to the ivoa doc repo.

**Comment by lmichel** [comment]
The names of the VODML files are as follow: `Model-vMAJOR.MINOR.vodml.xml`.
They must be published as such but the document coordinator must write a Apache rewriting rule in such a way that
the URL `Model-vMAJOR.vodml.xml` points onto `Model-vMAJOR.MINOR.vodml.xml.`

In your case, you must publish the file `PhotDM-v1.1.vodml.xml` as it is and ask Giulia the make a rewriting rule making it visible as` PhotDM-v1.vodml.xml`  .

Giulia knows the process.

**Comment by loumir** [comment]
solved in PR #103
