### ISSUE TITLE
Adding photcal serializations into the repo

### ISSUE THREAD

**Issue by lmichel** [ivoa-std/PhotDM#23]
We could make a directory, e.g. `serializations` containing all Photcal serializations made for the SED builder.
I can do it if you agree

**Comment by jesusjuansalgado** [comment]
It looks to me a good idea

**Comment by lmichel** [comment]
Done with an update of the README.
I let you check while the PDF generation doesn't work.

**Comment by loumir** [comment]
ok for the serialization directory
